name: Build

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://test.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  BASE_URL: http://localhost:5000
  GIT_COMMIT: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      # note currently PACT_PROVIDER isn't used in the code
        pact_provider:
          [
            "pactflow-example-provider-python",
            # "pactflow-example-bi-directional-provider-dredd",
            # "pactflow-example-bi-directional-provider-restassured",
            # "pactflow-example-bi-directional-provider-postman",
            # "pactflow-example-bi-directional-provider",
            # 'pactflow-example-bi-directional-provider-dotnet'
          ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.13' 
          architecture: 'x64' 
      - run: pip install -r requirements.txt
      - name: Test pactflow-example-consumer-python against ${{ matrix.pact_provider }}
        run: make test
        env:
          PACT_PROVIDER: ${{ matrix.pact_provider }}
      - name: Publish pacts
        run: GIT_BRANCH=${GIT_REF:11} make publish_pacts
        env:
          PACT_PROVIDER: ${{ matrix.pact_provider }}

  # Runs on branches as well, so we know the status of our PRs
  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Can I deploy?
        run: GIT_BRANCH=${GIT_REF:11} make can_i_deploy

  # Only deploy from master
  deploy:
    runs-on: ubuntu-latest
    needs: can-i-deploy
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Deploy
        run: GIT_BRANCH=${GIT_REF:11} make deploy
        if: github.ref == 'refs/heads/master'
